# Generated by Django 3.2.7 on 2021-09-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c', models.BooleanField(default=False, verbose_name='C')),
                ('cpp', models.BooleanField(default=False, verbose_name='C++')),
                ('ruby', models.BooleanField(default=False, verbose_name='Ruby on Rails')),
                ('perl', models.BooleanField(default=False, verbose_name='Perl')),
                ('java', models.BooleanField(default=False, verbose_name='Java')),
                ('asp', models.BooleanField(default=False, verbose_name='ASP')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
    ]
